# Source this first since it contains the locations of directories needed by funcitons
source "$HOME/.exports"
source "$HOME/.functions"
source "$HOME/.aliases"

eval "$(/opt/homebrew/bin/brew shellenv)"

# asdf
. /opt/homebrew/opt/asdf/libexec/asdf.sh

## Postgres
# export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
