#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################
export ME=$(whoami)

export TERM='rxvt-256color'
export DOTFILES="$HOME/.dotfiles"

[ -f "$DOTFILES/install_config" ] && source "$DOTFILES/install_config"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# editor
export EDITOR="code"
export GIT_EDITOR="code -w"
export VISUAL="code"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"        # History filepath
export HISTSIZE=10000                       # Maximum events for internal history
export SAVEHIST=10000                       # Maximum events in history file

# other software
export GPG_TTY=$(tty)
export I3_CONFIG="$XDG_CONFIG_HOME/i3"
export SCREENSHOT="$HOME/Documents/screenshots"
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

# golang
export GOPATH="$HOME/workspace/go"
export GOBIN="$HOME/workspace/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# git
export GIT_MERGE_AUTOEDIT='no'              # require message when merging
export GIT_REVIEW_BASE=main                 # see gitconfig

# PATH
export PATH="$GOBIN:$PATH"                  # GOBIN
export PATH="$NPM_BIN:$PATH"                # NPM
export PKG_CONFIG_PATH=/usr/bin/pkg-config
export STARSHIP_CONFIG=~"$HOME/.config/starship/starship.toml"

export PATH_TO_PLAYGROUND="$HOME/playground"
export PATH_TO_PROJECTS="$HOME/Projects"
export PATH_TO_JOURNAL="$HOME/journal"

# Cloud
# TODO: add path to private cloud for secrets
# source $CLOUD/development/env
